server:
  port: 8091
management:
  endpoints:
    web:
      exposure:
        include: *
eureka:
  instance:
    hostname: ${IPADDRESS:localhost}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  datasource:
    url: mongodb://${IPADDRESS:localhost}:27017/medilabo
