server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: *
eureka:
  instance:
    hostname: ${IPADDRESS:localhost}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://${IPADDRESS:localhost}:3306/medilabo
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
